apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-my-bitcoin
spec:
  selector:
    matchLabels:
      app: api-my-bitcoin
  template:
    metadata:
      labels:
        app: api-my-bitcoin
    spec:
      containers:
        - name: api-my-bitcoin
          image: paulohsv/api-mybtc:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http